---
language: python
cache: pip

stages:
  - test
  - name: deploy
    if: tag IS present
  - docsite
  - coverage

before_install:
  - pip uninstall pipenv numpy -y
  - pip install poetry

install:
  - poetry install

jobs:
  fast_finish: true
  include:
    - stage: test
      script:
        - inv qa.autoformat --check
        - inv qa.lint
        - inv qa.unit-test
        - inv qa.static-analysis

    - stage: deploy
      script: poetry config pypi-token.pypi $PYPI_TOKEN
      before_deploy: poetry build
      deploy:
        provider: script
        script: poetry publish
        skip_cleanup: true
        on:
          tags: true

    - stage: docsite
      script:
        - inv doc.lint
        - inv doc.test
        - inv doc.coverage  
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        keep_history: true
        on:
          branch: master

    - stage: coverage
      script:
        - inv qa.coverage --report=xml
        - bash <(curl -s https://codecov.io/bash)
