---
name: MkDocs
on:
  workflow_run:
    workflows: ['CI build']
    types:
      - completed
jobs:
  lint:
    runs-on: ubuntu-latest
    env:
       PATH: "${HOME}/.local/bin:${PATH}"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          fetch-depth: 0
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[build,docs]
      - name: Lint documentation
        run: |
          invoke doc.lint
          invoke doc.test
  build:
    runs-on: ubuntu-latest
    needs: lint
    env:
       PATH: "${HOME}/.local/bin:${PATH}"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          fetch-depth: 0
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[build,docs]
      - name: Perform documentation tests
        run: |
          invoke doc.coverage
          invoke doc.build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          fetch-depth: 0
      - name: 'Set up Python 3.10'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Lint documentation
        run: |
          python -m doctest README.md
